name: RandomJoinMessages
version: '${project.version}'
main: net.fauxfemale.randomjoinmessages.RJMPlugin
api-version: 1.19
authors: [ Shelly B "FauxFemale" ]
description: Allows you to create a list of random messages to show a player when they join
website:

commands:
  rjm:
    description: Reload and view version of RandomJoinMessages
    usage: /<command> [reload]